"""add user ban fields

Revision ID: ccf06500088f
Revises: 932e187b017f
Create Date: 2025-05-15 22:21:07.862870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccf06500088f'
down_revision = '932e187b017f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('banned', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('ban_type', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('ban_until', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('ban_until')
        batch_op.drop_column('ban_type')
        batch_op.drop_column('banned')

    # ### end Alembic commands ###
